#!/bin/bash

# build on a separate branch from working branch so
# node_modules / bower_modules aren't wiped out
git branch -D gh-pages-pre-commit
git checkout -b gh-pages-pre-commit

# build, move to the first level directory, only keep
# built files for pending gh-pages push
ember build
mv dist/index.html .
mv dist/assets .
mv dist/images .
rm -rf !(index.html|assets|images)

# prepare fresh gh-pages branch and push
git branch -D gh-pages
git checkout -b gh-pages
git add .
git commit -m "gh-pages updated"
git push -u origin gh-pages --force-with-lease
